apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregated-apiserver-operator
  namespace: aggregated-apiserver-operator
  labels:
    app.kubernetes.io/name: aggregated-apiserver-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aggregated-apiserver-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aggregated-apiserver-operator
    spec:
      serviceAccountName: aggregated-apiserver-operator
      containers:
        - name: operator
          image: ghcr.io/ntnn/aggregated-apiserver-operator/operator:latest
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
