apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - api-aggregator-serviceaccount.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - ../crd
  - ../rbac/operator
  - ../rbac/api-aggregator
